### ISSUE TITLE
be careful using parallel bootstrap in conjunction with fitting routine

### ISSUE THREAD

**Issue by luhuhis** [LatticeQCD/LatticeToolbox#5]
This can spawn a large number of threads, because it uses concurrent.futures in the bootstrap, as well as the multiprocessing module in optimize.py, where the minimum search is performed for the fits!

**Comment by clarkedavida** [comment]
I used recently the curve_fit wrapper inside a parallel bootstrap and I didn't notice any problems...

If I don't hear anything else about this issue by the time I remember to look at it again, I will probably just close it.

**Comment by clarkedavida** [comment]
I think I specified 8 threads. Did you experience this locally or on the cluster?

**Comment by luhuhis** [comment]
On the cluster in bielefeld (login node)
Could you try to reproduce the issue? Just run the wrapper again inside a bootstrap and monitor how many cores it's using.

**Comment by clarkedavida** [comment]
optimize.py doesn't seem to be using multiprocessing (maybe it did in the past?), and i've never encountered this bug, so i'm closing the issue.
